In [18]:
!pip -q install transformers torch pandas

In [2]:
import torch
import pandas as pd
from transformers import GPT2LMHeadModel, GPT2Tokenizer

In [3]:
model_name = "gpt2"

tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

model.eval()

print("GPT-2 model loaded successfully.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

GPT-2 model loaded successfully.

In [4]:
def generate_text(prompt, temperature=1.0, top_k=50, top_p=1.0,
                  repetition_penalty=1.0):

    input_ids = tokenizer.encode(prompt, return_tensors="pt")

    with torch.no_grad():
        output = model.generate(
            input_ids,
            max_new_tokens=80,
            do_sample=True,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p,
            repetition_penalty=repetition_penalty,
            pad_token_id=tokenizer.eos_token_id
        )

    generated = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    return generated

In [5]:
original_prompt = "The old house at the end of the street had been empty for years, until one evening"
print(original_prompt)

The old house at the end of the street had been empty for years, until one evening

In [6]:
text_1 = generate_text(
    original_prompt,
    temperature=1.0,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.0
)

print(text_1)

The old house at the end of the street had been empty for years, until one evening a few years ago. A man went past on the street trying to find someone. The old man's family drove to Al-Daniya and got two pieces of good news: a car and a dog. The man called them from a very nice little villa. The Old Man said he had a son – I think he was about four years old. I told him I was going to

In [7]:
text_2 = generate_text(
    original_prompt,
    temperature=0.4,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.0
)

print(text_2)

The old house at the end of the street had been empty for years, until one evening, the old man came out and asked me to come with him. I was not a man of the house, but I had been here for a long time, and I had heard the old man tell me that he had been here for a long time. He said that he had been here for a long time, and that he had been here for a long time. I said, "Well

In [8]:
text_3 = generate_text(
    original_prompt,
    temperature=1.5,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.0
)

print(text_3)

The old house at the end of the street had been empty for years, until one evening, the woman had asked his friend to take her home after her father broke up from the business which kept them both busy and was still running out. Mr Shabik came over here to offer his blessings and had heard only about its destruction once that night. He left in an all night walk.


He never left all night's day. The rest was history by him.


When

In [9]:
text_4 = generate_text(
    original_prompt,
    temperature=1.0,
    top_k=10,
    top_p=1.0,
    repetition_penalty=1.0
)

print(text_4)

The old house at the end of the street had been empty for years, until one evening he got out and found some old man lying on the ground. He was very angry, and he had no intention of letting him out, but he did not take pity on him. When he heard his cry, he went and got him a chair and a chair-cloth. The man had taken a piece of bread from one of the little boys in the house, and then, as soon as

In [10]:
text_5 = generate_text(
    original_prompt,
    temperature=1.0,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.4
)

print(text_5)

The old house at the end of the street had been empty for years, until one evening I stopped by and asked this person what his intention was. She told me that they were going on a vacation to find some rest in town—they came up with several ways out but couldn't really stop her since it is too cold before bedtime," he tells us from an early stage during my study session near Rt 1503/302913:
In recent days (January 12),

In [11]:
experiment_data = {
    "Experiment": [
        "1 - Default",
        "2 - Low Temperature",
        "3 - High Temperature",
        "4 - Low Top-k",
        "5 - Repetition Penalty"
    ],

    "Parameter Changed": [
        "Default",
        "Temperature",
        "Temperature",
        "Top-k",
        "Repetition Penalty"
    ],

    "Value": [
        "1.0",
        "0.4",
        "1.5",
        "10",
        "1.4"
    ],

    "Generated Output": [
        text_1,
        text_2,
        text_3,
        text_4,
        text_5
    ]
}

comparison = pd.DataFrame(experiment_data)

comparison

,Experiment,Parameter Changed,Value,Generated Output
0,1 - Default,Default,1.0,The old house at the end of the street had bee...
1,2 - Low Temperature,Temperature,0.4,The old house at the end of the street had bee...
2,3 - High Temperature,Temperature,1.5,The old house at the end of the street had bee...
3,4 - Low Top-k,Top-k,10,The old house at the end of the street had bee...
4,5 - Repetition Penalty,Repetition Penalty,1.4,The old house at the end of the street had bee...

In [12]:
custom_prompt = (
    "Our small bakery opened its doors on a rainy Sunday morning, "
    "and something unexpected happened"
)

print(custom_prompt)

Our small bakery opened its doors on a rainy Sunday morning, and something unexpected happened

In [13]:
custom_1 = generate_text(
    custom_prompt,
    temperature=1.2,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.1
)

print(custom_1)

Our small bakery opened its doors on a rainy Sunday morning, and something unexpected happened as they arrived there. We all saw the signs of life inside it - black crescent shaped buildings hanging overhead from trees looking out in clear view with their reflective windows covered by rainforest leaf – but even before my friends were allowed to get back here I was worried that some strange phenomenon had caught fire causing panic at our local Starbucks for which everyone called me when we started eating food outside alone together:

In [14]:
custom_2 = generate_text(
    custom_prompt,
    temperature=0.6,
    top_k=30,
    top_p=1.0,
    repetition_penalty=1.1
)

print(custom_2)

Our small bakery opened its doors on a rainy Sunday morning, and something unexpected happened.
The shop was not open for business until the afternoon of April 9th when it closed to make way for our new home at 535 W North Ave in San Francisco's Mission District (which is also where we were born). We had never heard about this store before so I thought maybe they would be interested in helping us out with some food preparation stuff that might help you get started! However

In [15]:
custom_3 = generate_text(
    custom_prompt,
    temperature=1.4,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.2
)

print(custom_3)

Our small bakery opened its doors on a rainy Sunday morning, and something unexpected happened: after just three pies they became the breadstuffs that you can almost go into your heart without tasting it or drinking. At one point about 6 of us would even pull at our underwear with duct tape to see where all this dough was coming from—but only for 3 hours! The store looked familiar—"there might be some food there"—and we knew what did go down well inside since no

In [16]:
custom_results = pd.DataFrame({
    "Version": ["Version 1", "Version 2", "Version 3"],
    "Setting": [
        "Temperature = 1.2",
        "Temperature = 0.6, Top-k = 30",
        "Temperature = 1.4"
    ],
    "Generated Text": [
        custom_1,
        custom_2,
        custom_3
    ]
})

custom_results

,Version,Setting,Generated Text
0,Version 1,Temperature = 1.2,Our small bakery opened its doors on a rainy S...
1,Version 2,"Temperature = 0.6, Top-k = 30",Our small bakery opened its doors on a rainy S...
2,Version 3,Temperature = 1.4,Our small bakery opened its doors on a rainy S...

In [17]:
unusual_prompt = "The robot walked into the classroom and suddenly"

strange_output = generate_text(
    unusual_prompt,
    temperature=2.0,
    top_k=50,
    top_p=1.0,
    repetition_penalty=1.0
)

print(strange_output)

The robot walked into the classroom and suddenly went up above the room where the main window hung up...

At full height this robot could walk over anything without ever looking outside it's nose, a small room at the top of several rows of glass shelves. It looked vaguely, possibly, though I suspect her body language must have used the same vocabulary.

Her teacher came running straight when she reached it, looking like they'd both